mutation PostCourse($course: CourseInput!) {
  postCourse(course: $course) {
    id
    name
    coursePath
    courseFilename
    subjectId
    userId
    professor {
      id
      name
      surname
      title
    }
    subject {
      id
      name
    }
  }
}
