version: '3.5'
services:
  user-ui:
    container_name: user-ui
    build: .
    environment:
      - NODE_ENV=production
      - VUE_APP_GRAPHQL_HTTP=http://localhost:3000/graphql
      - VUE_APP_GRAPHQL_WS=ws://localhost:3000/graphql
      - VUE_APP_ACCESS_TOKEN=schoolar:access
    ports:
      - "80:80"

networks:
  default:
    name: schoolar-network

