query Subjects($facultyId: ID!) {
  subjects: subjectsByFacultyId(facultyId: $facultyId) {
    id
    name
    credits
    facultyId
    courses {
      id
      name
      coursePath
      courseFilename
      subjectId
      userId
    }
  }
}
