query Events(
  $id: ID!
) {
  event(id: $id) {
    id
    room
    startTime
    endTime
    subjectId
    eventTypeId
    userId
    professor {
      id
      title
      name
      surname
    }
    subject {
      id
      name
    }
    eventType {
      id
      type
    }
  }
}
