query Event($id: ID!) {
  event(id: $id) {
    id
    room
    subjectId
    eventTypeId
    startTime
    endTime
    userId
    professor {
      id
      name
      surname
      title
    }
    subject {
      id
      name
    }
    eventType {
      id
      type
    }
    results {
      id
      testId
      startPeriod
      endPeriod
      testId
      eventId
      test {
        id
        title
        description
        questions {
          id
        }
      }
      sessionAnswers {
        id
        isCorrect
      }
    }
  }
}
