query Events($userId: ID, $startDate: String, $endDate: String, $groupId: ID) {
  events: eventsByQuery(
    userId: $userId
    startDate: $startDate
    endDate: $endDate
    groupId: $groupId
  ) {
    id
    room
    date
    startTime
    endTime
    isFullDay
    isNotifiable
    subjectId
    groupId
    eventTypeId
    userId
    group {
      id
      number
    }
    subject {
      id
      name
    }
    eventType {
      id
      type
      color
    }
  }
}
