query StudentEvents(
  $groupId: ID
  $startDate: String!
  $endDate: String!
  $userId: ID
) {
  events: eventsByQuery(
    groupId: $groupId
    startDate: $startDate
    endDate: $endDate
    userId: $userId
  ) {
    id
    room
    date
    startTime
    endTime
    subjectId
    eventTypeId
    userId
    eventId
    professor {
      id
      title
      name
      surname
    }
    subject {
      id
      name
    }
    eventType {
      id
      type
      color
    }
  }
}
