query Events(
  $groupId: ID!,
  $startDate: String!
  $endDate: String!
) {
  events: eventsByQuery(
    groupId: $groupId
    startDate: $startDate
    endDate: $endDate
  ) {
    id
    room
    date
    startTime
    endTime
    isFullDay
    isNotifiable
    subjectId
    eventTypeId
    professorId
    professor {
      id
      title
      name
      surname
    }
    subject {
      id
      name
    }
    eventType {
      id
      type
      color
    }
  }
}
