mutation PostQuestion($question: QuestionInput!) {
  postQuestion(question: $question) {
    id
    description
    rating
    userId
    isVoted
    sessionId
    answer {
      id
      description
      questionId
    }
  }
}