query Question($id: ID!) {
  question: question(id: $id) {
    id
    description
    rating
    userId
    isVoted
    ratingObj {
      id
      userId
      questionId
    }
    answer {
      id
      description
      questionId
    }
  }
}
