query Questions($sessionId: ID!) {
  questions: questions(sessionId: $sessionId) {
    id
    description
    rating
    isVoted
    sessionId
    userId
    ratingObj {
      id
      userId
      questionId
    }
    answer {
      id
      description
      questionId
    }
  }
}
