mutation UpdateQuestion($question: QuestionInput!) {
  updateQuestion(question: $question) {
    id
    description
    rating
    userId
    isVoted
    sessionId
    ratingObj {
      id
      userId
      questionId
    }
    answer {
      id
      description
      questionId
    }
  }
}
