subscription UpdateQuestionSubscription {
  updateQuestion {
    id
    description
    rating
    userId
    isVoted
    sessionId
    ratingObj {
      id
      userId
      questionId
    }
    answer {
      id
      description
      questionId
    }
  }
}
