mutation PostQuizSession($session: QuizSessionInput!) {
  postQuizSession(session: $session) {
    id
    code
    duration
    eventId
    event {
      subjectId
      eventTypeId
      subject {
        name
      }
      eventType {
        type
      }
    }
    startPeriod
    endPeriod
    test {
      id
      description
    }
  }
}
