query ProfessorQuizSession($id: ID!) {
  quizSession: quizSession(id: $id) {
    id
    code
    duration
    startPeriod
    endPeriod
    eventId
    test {
      id
      questions {
        id
      }
    }
    event {
      subjectId
      subject {
        name
      }
    }
    userSessions {
      id
      userId
      status
      startedAt
    }
    userAnswers {
      id
      sessionId
      userId
      questionId
      isCorrect
    }
  }
}