subscription ProfessorQuizSessionSubscription {
  postJoinQuizSession {
      id
      userId
      joinedAt
      student {
        name
        surname
        groupId
        group {
          number
        }
      }
  }
}
