query ProfessorQuizSession($id: ID!) {
  quizSession: quizSession(id: $id) {
    id
    code
    duration
    score
    startPeriod
    endPeriod
    userSessions {
      id
      userId
      joinedAt
    }
  }
}