query ProfessorQuizSession($id: ID!) {
  quizSession: quizSession(id: $id) {
    id
    code
    duration
    score
    startPeriod
    endPeriod
    eventId
    event {
      subjectId
      subject {
        name
      }
    }
    userSessions {
      id
      userId
      status
      joinedAt
    }
  }
}