query StudentQuizSession($code: String!) {
  quizSession: quizSessionByCode(code: $code) {
    id
    code
    duration
    startPeriod
    endPeriod
    testId
    userSession {
      id
      startedAt
      status
    }
    userAnswers {
      id
      questionId
      answerId
      isCorrect
    }
    eventId
    event {
      subjectId
      subject {
        name
      }
    }
    test {
      title
      description
      subjectId
      subject {
        name
      }
      questions {
        id
        imagePath
        description
        answers {
          id
          description
        }
      }
    }
  }
}
