query TestQuery($id: ID!) {
  test: test(id: $id) {
    id
    title
    description
    subjectId
    subject {
      id
      name
    }
    questions {
      id
      description
      imagePath
    }
  }
}