mutation UpdateTest($test: QuizTestInput!) {
  updateTest(test: $test) {
    id
    title
    description
    subjectId
    subject {
      id
      name
    }
    questions {
      id
      description
    }
  }
}